# Generated by Django 4.2.1 on 2023-07-03 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_item_despensa_alter_item_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categoria',
        ),
    ]
