# Generated by Django 4.2.1 on 2023-07-03 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_remove_categoria_item'),
        ('item', '0004_remove_item_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='categoria.categoria'),
        ),
    ]
