# Generated by Django 4.2.1 on 2023-07-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0004_remove_despensa_usuarios'),
        ('core', '0004_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='despensas',
            field=models.ManyToManyField(blank=True, to='despensa.despensa'),
        ),
    ]
