# Generated by Django 4.2.1 on 2023-06-10 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='codigo_id',
        ),
    ]
