# Generated by Django 4.2.1 on 2023-07-03 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0003_despensa_usuarios'),
        ('categoria', '0001_initial'),
        ('item', '0002_remove_item_codigo_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='despensa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='despensa.despensa'),
        ),
        migrations.AlterField(
            model_name='item',
            name='categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='categoria.categoria'),
        ),
    ]
