# Generated by Django 4.2.1 on 2023-07-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0002_categoria_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='item',
        ),
    ]
