# Generated by Django 4.2.1 on 2023-07-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0006_remove_despensa_capacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despensa',
            name='quantTotal',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
