# Generated by Django 4.2.1 on 2023-06-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despensa',
            name='categoria',
        ),
    ]
