# Generated by Django 4.2.1 on 2023-07-03 21:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('despensa', '0002_remove_despensa_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='despensa',
            name='usuarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
