# Generated by Django 4.2.1 on 2023-07-14 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0005_despensa_usuarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despensa',
            name='capacidade',
        ),
    ]
