# Generated by Django 4.2.1 on 2023-07-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despensa', '0008_alter_despensa_quanttotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despensa',
            name='quantTotal',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
